### ISSUE TITLE
Looks interesting but use cases not entirely clear

### ISSUE THREAD

**Issue by fullofcaffeine** [chancedickson/isorender-node#5]
Hi!

Found this lib while looking for a good way to SSR React in a Phoenix app. Found this message in the reddit thread https://www.reddit.com/r/elixir/comments/8pskrg/what_is_the_recommended_solution_for_react_server/ suggesting this lib.

It's not clear what are the real-world use-cases for this though, at least not when compared to just using a regular express server o, in the case of a simpler stdin-based one, why not just outputing the whole HTML with process.stdout? It'd be great if you could add a section about this in the README. 

Thank you!

**Comment by pheebcodes** [comment]
A project I was working on used this code for communication between Elixir and Node.js. The Elixir project would have long-running [Port](https://hexdocs.pm/elixir/1.12/Port.html) backed by a Node.js process. Elixir would communicate through the Port to Node.js, Node.js would respond with the resulting HTML, Elixir would send that HTML in the response. This library was specifically for handling the stdin/stdout communication and message encoding used by Ports on the Node.js side, but it's since been removed from npm so it's no longer usable in it's current state.

As for _why_ we chose that approach compared to others, I don't remember. :) This repo hasn't actually been touched for a bit over 6 years and I haven't used Elixir in about the same amount of time, so I don't remember enough about the tradeoffs we were making at the time to elaborate on why anyone would/should use this approach.
